-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.substation
(
    substation_id integer NOT NULL,
    name text,
    latitude numeric,
    longitude numeric,
    region text NOT NULL,
    rating numeric,
    day_max_demand numeric,
    night_max_demand numeric
);

COMMENT ON TABLE public.substation
    IS 'Stores information about the distribution substation properties.';

COMMENT ON COLUMN public.substation.substation_id
    IS 'Each substation should have its id which is defined by UK National Grid or SSEN';

COMMENT ON COLUMN public.substation.name
    IS 'The name of the substation';

COMMENT ON COLUMN public.substation.rating
    IS 'The maximum capacity that the substation can handle. Units are in kVA';

COMMENT ON COLUMN public.substation.day_max_demand
    IS 'The maximum electricity demand recorded during daytime hours.';

COMMENT ON COLUMN public.substation.night_max_demand
    IS 'The maximum electricity demand recorded during nighttime hours.';
END;