-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.region
(
    region_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    region text NOT NULL,
    PRIMARY KEY (region_id)
);

COMMENT ON TABLE public.region
    IS 'Different regions in the entire United Kingdom';

CREATE TABLE IF NOT EXISTS public.substation
(
    substation_id integer NOT NULL,
    latitude numeric NOT NULL,
    longitude numeric NOT NULL,
    region_id integer NOT NULL
);

COMMENT ON TABLE public.substation
    IS 'Stores information about the substation properties';

ALTER TABLE IF EXISTS public.substation
    ADD CONSTRAINT substation_region_id FOREIGN KEY (region_id)
    REFERENCES public.region (region_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;

END;