-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.substation
(
    substation_id integer NOT NULL,
    name text,
    latitude numeric,
    longitude numeric,
    region text NOT NULL,
    rating numeric,
    day_max_demand numeric,
    night_max_demand numeric
);

COMMENT ON TABLE public.substation
    IS 'Stores information about the distribution substation properties.';

COMMENT ON COLUMN public.substation.substation_id
    IS 'Each substation should have its id which is defined by UK National Grid or SSEN';

COMMENT ON COLUMN public.substation.name
    IS 'The name of the substation';

COMMENT ON COLUMN public.substation.rating
    IS 'The maximum capacity that the substation can handle. Units are in kVA';

COMMENT ON COLUMN public.substation.day_max_demand
    IS 'The maximum electricity demand recorded during daytime hours.';

COMMENT ON COLUMN public.substation.night_max_demand
    IS 'The maximum electricity demand recorded during nighttime hours.';

CREATE TABLE IF NOT EXISTS public.embeddings
(
    id text NOT NULL,
    content text NOT NULL,
    embedding vector(1536) NOT NULL,
    metadata jsonb,
    content_tsv tsvector NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.embeddings
    IS 'Stores OpenAI text-embedding-3-small vectors for EV knowledge base chunks.';

CREATE TABLE IF NOT EXISTS public.vehicle_profiles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    make text NOT NULL,
    model text NOT NULL,
    "trim" text,
    model_year integer NOT NULL,
    total_battery_capacity_kwh numeric NOT NULL,
    usable_battery_capacity_kwh numeric NOT NULL,
    vehicle_class text NOT NULL,
    chemistry text NOT NULL,
    "peak_dc_power_kW" numeric NOT NULL,
    curve_type text NOT NULL,
    curve_points jsonb NOT NULL,
    source_url text,
    notes text,
    CONSTRAINT uq_vehicle_variant UNIQUE (make, model, "trim", model_year, total_battery_capacity_kwh)
);

COMMENT ON TABLE public.vehicle_profiles
    IS 'Reference charge curve profiles per vehicle variant.';
END;